connector.name=iceberg
iceberg.catalog.type=hadoop
iceberg.catalog.warehouse=s3a://lakehouse/
fs.s3a.endpoint=http://minio:9000
fs.s3a.access.key=minioadmin
fs.s3a.secret.key=minioadmin
fs.s3a.path.style.access=true
