spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.my_catalog.type=hadoop
spark.sql.catalog.my_catalog.warehouse=s3a://lakehouse/
spark.sql.catalog.my_catalog.hadoop.fs.s3a.endpoint=http://minio:9000
spark.sql.catalog.my_catalog.hadoop.fs.s3a.access.key=minioadmin
spark.sql.catalog.my_catalog.hadoop.fs.s3a.secret.key=minioadmin
spark.sql.catalog.my_catalog.hadoop.fs.s3a.path.style.access=true
